// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE6ekSVIXWN9Nc-iKqQPxAH8-9Z0PmtJ8',
    appId: '1:426539055960:web:bcbca189a80c9f4b5dc32d',
    messagingSenderId: '426539055960',
    projectId: 'booksexchange-5241f',
    authDomain: 'booksexchange-5241f.firebaseapp.com',
    storageBucket: 'booksexchange-5241f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0IKG0XbhKKCqCSuS0SCTmQIicV4U7TGo',
    appId: '1:426539055960:android:69db24938caa1e7f5dc32d',
    messagingSenderId: '426539055960',
    projectId: 'booksexchange-5241f',
    storageBucket: 'booksexchange-5241f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXc_FLHxaT0ZmWQHP8620csk8X4CydjC8',
    appId: '1:426539055960:ios:d155335e1a55da055dc32d',
    messagingSenderId: '426539055960',
    projectId: 'booksexchange-5241f',
    storageBucket: 'booksexchange-5241f.appspot.com',
    iosBundleId: 'com.example.booksexchange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXc_FLHxaT0ZmWQHP8620csk8X4CydjC8',
    appId: '1:426539055960:ios:d155335e1a55da055dc32d',
    messagingSenderId: '426539055960',
    projectId: 'booksexchange-5241f',
    storageBucket: 'booksexchange-5241f.appspot.com',
    iosBundleId: 'com.example.booksexchange',
  );
}
